### ISSUE TITLE
pr0 normen

### ISSUE THREAD

**Issue by HSoeren** [pr0tools/pr0tools#3]
Sicher nicht die cleverste Anfrage aber keine Ahnung,.

Es gab meines Wissens nach bisher 4 Anläufe die Tiernamen nach pr0 zu normieren; also *kefer etc. Falls es möglich wäre fände ich es praktisch die auf pr0.tools verlinkt zu haben, dann muss ich nicht suchen, wenn ich nachschlafen will wie die .EXE oder der Kefer heißt :)

**Comment by pr0tools** [comment]
https://github.com/RundesBalli/pr0tools/issues

@rundesballi
